version: '3'

services:
    nodejs-app:
        build:
          context: ./backend
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "3001:3001" 
        networks:
            - example-net
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "81:81" 
        depends_on:
            - nodejs-app
        networks:
            - example-net

networks:
  example-net:
    external: true